Rails.application.config.assets.precompile += %w( application.css )
Rails.application.config.assets.precompile += %w( redaction.css )
Rails.application.config.assets.precompile += %w( application.js )
Rails.application.config.assets.precompile += %w( share.js )
Rails.application.config.assets.precompile += %w( redaction.js )
